import sys
def errAndExit(e):

    sys.exit(1)
